=== gapsong/Xml-Technologie/Mancala(Long)/spielzustand.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT spielfeld (spiel, mulde+,haus+)>

<!ELEMENT spiel (gewonnen, istAmZug)>
<!ELEMENT gewonnen (#PCDATA)>
<!ELEMENT istAmZug (#PCDATA)>

<!ELEMENT mulde (anzahlSteine,posX,posY)>
     <!ATTLIST mulde
      besitzer CDATA #REQUIRED
      id CDATA #REQUIRED>
<!ELEMENT anzahlSteine (#PCDATA)>  
<!ELEMENT posX (#PCDATA)>
<!ELEMENT posY (#PCDATA)>
  
<!ELEMENT haus (anzahlSteineimHaus)>
    <!ATTLIST haus
      besitzer CDATA #REQUIRED>
<!ELEMENT anzahlSteineimHaus (#PCDATA)>

=== gapsong/Xml-Technologie/Mancala(Long)/spielstartzustand.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spielfeld SYSTEM "spielzustand.dtd">
<?xml-stylesheet type="text/xsl" href="spielzustand.xsl"?>
<spielfeld>
    <spiel>
        <gewonnen>nein</gewonnen>
        <istAmZug>spieler2</istAmZug>
    </spiel>

    <mulde besitzer="1" id="6">
        <anzahlSteine> 13 </anzahlSteine>
        <posX>20.5%</posX>
        <posY>23%</posY>
    </mulde>
    <mulde besitzer="1" id="5">
        <anzahlSteine> 14 </anzahlSteine>
        <posX>30%</posX>
        <posY>23%</posY>
    </mulde>
    <mulde besitzer="1" id="4">
        <anzahlSteine> 14 </anzahlSteine>
        <posX>39.5%</posX>
        <posY>23%</posY>
    </mulde>
    <mulde besitzer="1" id="3">
        <anzahlSteine> 5</anzahlSteine>
        <posX>49%</posX>
        <posY>23%</posY>
    </mulde>
    <mulde besitzer="1" id="2">
        <anzahlSteine> 8 </anzahlSteine>
        <posX>58.5%</posX>
        <posY>23%</posY>
    </mulde>
    <mulde besitzer="1" id="1">
        <anzahlSteine> 12 </anzahlSteine>
        <posX>68%</posX>
        <posY>23%</posY>
    </mulde>

    <mulde besitzer="2" id="6">
        <anzahlSteine> 12 </anzahlSteine>
        <posX>68%</posX>
        <posY>65%</posY>
    </mulde>
    <mulde besitzer="2" id="5">
        <anzahlSteine> 4 </anzahlSteine>
        <posX>58.5%</posX>
        <posY>65%</posY>
    </mulde>
    <mulde besitzer="2" id="4">
        <anzahlSteine> 4 </anzahlSteine>
        <posX>49%</posX>
        <posY>65%</posY>
    </mulde>
    <mulde besitzer="2" id="3">
        <anzahlSteine> 4 </anzahlSteine>
        <posX>39.5%</posX>
        <posY>65%</posY>
    </mulde>
    <mulde besitzer="2" id="2">
        <anzahlSteine> 4 </anzahlSteine>
        <posX>30%</posX>
        <posY>65%</posY>
    </mulde>
    <mulde besitzer="2" id="1">
        <anzahlSteine> 4 </anzahlSteine>
        <posX>20.5%</posX>
        <posY>65%</posY>
    </mulde>

    <haus besitzer="1">
        <anzahlSteineimHaus> 1 </anzahlSteineimHaus>
    </haus>

    <haus besitzer="2">
        <anzahlSteineimHaus> 2 </anzahlSteineimHaus>
    </haus>
</spielfeld>

=== gapsong/Xml-Technologie/Mancala/unsermancala.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spielfeld SYSTEM "spielzustand.dtd">
<?xml-stylesheet type="text/xsl" href="Untitled2.xsl"?>

<spielfeld>
    <spiel>
        <gewonnen>nein</gewonnen>
        <istAmZug>spieler1</istAmZug>
    </spiel>
    
    <mulde  besitzer="1" id="1">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="1" id="2">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="1" id="3">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="1" id="4">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="1" id="5">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="1" id="6">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    
    <mulde  besitzer="2" id="1">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="2" id="2">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="2" id="3">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="2" id="4">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="2" id="5">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    <mulde  besitzer="2" id="6">
        <anzahlSteine> 4 </anzahlSteine>    
    </mulde>
    
    <haus besitzer="1">
        <anzahlSteineimHaus> 0 </anzahlSteineimHaus>
    </haus>
    
    <haus besitzer="2">
        <anzahlSteineimHaus> 0 </anzahlSteineimHaus>
    </haus>
</spielfeld>
